# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
 - gcc
notifications:
  email:
    on_success: never
    on_failure: change
    recipients:
      - deray.jeremie@gmail.com
env:
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu              UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".rosinstall" #NOT_TEST_INSTALL=true
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".rosinstall"  #NOT_TEST_INSTALL=true
    - ROS_DISTRO="kinetic"  PRERELEASE=true                                                     UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".rosinstall"
    - ROS_DISTRO="melodic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu              UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".rosinstall" #NOT_TEST_INSTALL=true
    - ROS_DISTRO="melodic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".rosinstall"  #NOT_TEST_INSTALL=true
    - ROS_DISTRO="melodic"  PRERELEASE=true                                                     UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME=".rosinstall"
matrix:
  allow_failures:
    # Run docker-based ROS prerelease test http://wiki.ros.org/bloom/Tutorials/PrereleaseTest
    # Because we might not want to run prerelease test for all PRs, it's omitted from pass-fail criteria.
    - env: ROS_DISTRO="kinetic" PRERELEASE=true
    - env: ROS_DISTRO="melodic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
